<?php
declare(strict_types=1);

return function (array $args, string $apiKey): array {
    $sitemap = (string) ($args['sitemap_url'] ?? '');
    $allowAi = ! isset($args['allow_ai']) || (bool) $args['allow_ai']; // default true
    $disallow = $args['disallow_paths'] ?? [];

    if ($sitemap === '' || ! filter_var($sitemap, FILTER_VALIDATE_URL)) {
        throw new \RuntimeException('sitemap_url is required and must be a full URL');
    }

    $aiBots = ['GPTBot', 'ChatGPT-User', 'ClaudeBot', 'anthropic-ai', 'PerplexityBot', 'Google-Extended'];

    $out = "# robots.txt — generated by Ranki.io MCP\n\n";
    $out .= "User-agent: *\n";
    if (is_array($disallow)) {
        foreach ($disallow as $path) {
            $path = trim((string) $path);
            if ($path === '') {
                continue;
            }
            if (! str_starts_with($path, '/')) {
                $path = '/'.$path;
            }
            $out .= "Disallow: {$path}\n";
        }
    }
    if (empty($disallow)) {
        $out .= "Disallow:\n";
    }
    $out .= "\n";

    if (! $allowAi) {
        $out .= "# AI crawlers blocked\n";
        foreach ($aiBots as $bot) {
            $out .= "User-agent: {$bot}\n";
            $out .= "Disallow: /\n\n";
        }
    } else {
        $out .= "# AI crawlers explicitly allowed (you want citation traffic from ChatGPT/Claude/Perplexity)\n";
        foreach ($aiBots as $bot) {
            $out .= "User-agent: {$bot}\n";
            $out .= "Allow: /\n\n";
        }
    }

    $out .= "Sitemap: {$sitemap}\n";

    return rk_mcp_text_content("Save as robots.txt at your site root:\n\n```\n{$out}\n```");
};
